version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./downloads:/app/downloads
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SAUCENAO_KEY=${SAUCENAO_KEY}
      - YT_KEY=${YT_KEY}

    restart: always
